FROM alpine
MAINTAINER Zeljko <mail@zeljko>

# Add repo file
ADD ./zeljko.repo /etc/yum.repos.d/

# Install cool software
RUN apk add bash nmap

ENTRYPOINT ["/usr/bin/nmap"]
CMD ["-sn", "172.17.0.0/24"] 
